name: 'testgen'
version: '0.0.1'

profile: postgres

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
log-path: "logs"