

{% set actual_yaml = toyaml(fromjson(tojson(
        testgen.get_range_test_suggestions(
            ref('colnames_with_spaces')
        )
    )))
%}

{% set expected_yaml %}
models:
- name: colnames_with_spaces
  columns:
  - name: Age (Years)
    description: Numeric range test generated by dbt-testgen
    tests:
    - dbt_utils.accepted_range:
        min_value: 22
        max_value: 30
{% endset %}

{{ assert_equal (actual_yaml | trim, expected_yaml | trim) }}