name: 'testgen_integration_tests'
version: '0.1'
config-version: 2

profile: 'integration_tests'

test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  +schema: integration_test_data
  +quote_columns: true

models:
  dbt_utils: # Hide "dbt_utils" package
    +docs:
      show: false