name: 'testgen_integration_tests'
version: '0.1'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  +schema: integration_test_data
  +quote_columns: true