config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  target: duckdb
  outputs:
    sqlite:
        type: sqlite
        threads: 1
        database: 'database'
        schema: 'main'
        schemas_and_paths:
            main: 'data/sqlite/integration_test_data.db'
        schema_directory: 'sqlite/'
        host: ''
    duckdb:
      type: duckdb
      path: 'data/duckdb/integration_test_data.duckdb'
    postgres:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
    mysql:
      type: mysql
      host: mysql
      username: mysql
      password: mysql
      port: 3306
      schema: public
    snowflake:
      type: snowflake
      account: ircmtcn-ekb34223
      # User/password auth
      user: DBT_TESTGEN
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: DBT_TESTGEN
      database: DBT_TESTGEN
      warehouse: DBT_TESTGEN
      schema: DBT_TESTGEN
      threads: 1
      client_session_keep_alive: False
      query_tag: DBT_TESTGEN
      outputs:
    redshift:
      type: redshift
      host: dbt-testgen.117819748843.us-east-1.redshift-serverless.amazonaws.com
      user: dbt_testgen
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      dbname: dbt_testgen
      schema: dbt_testgen
      port: 5439