

{% set actual_yaml = toyaml(fromjson(tojson(
        testgen.get_uniqueness_test_suggestions(
            ref('colnames_with_spaces'),
            composite_key_length = 1
        )
    )))
%}

{% set expected_yaml %}
models:
- name: colnames_with_spaces
  columns:
  - name: First Name
    description: Uniqueness test generated by dbt-testgen
    tests:
    - unique
    - not_null
  - name: Age (Years)
    description: Uniqueness test generated by dbt-testgen
    tests:
    - unique
    - not_null
  - name: Current City
    description: Uniqueness test generated by dbt-testgen
    tests:
    - unique
    - not_null
{% endset %}

{{ assert_equal (actual_yaml | trim, expected_yaml | trim) }}