

{% set input_yaml %}
models:
- name: users
  columns:
  - name: user_status
    description: Accepted values test generated by dbt-testgen
    tests:
    - accepted_values:
        values:
        - active
        - inactive
{% endset %}


{% set actual_yaml = toyaml(testgen.reformat_dbt_config(fromyaml(input_yaml))) %}


{% set expected_yaml %}
models:
    users:
        user_status:
            tests:
            - accepted_values:
                values:
                - active
                - inactive
{% endset %}

{{ assert_equal (actual_yaml | trim, expected_yaml | trim) }}