

{% set actual_yaml = testgen.to_yaml(
        testgen.get_test_suggestions(
            ref('users'),
            return_object=true
        )
    )
%}

{% set expected_yaml %}
models:
- name: users
  columns:
  - name: user_id
    description: Numeric range test generated by dbt-testgen
    tests:
    - unique
    - not_null
    - dbt_utils.accepted_range:
        min_value: 1
        max_value: 30
  - name: username
    description: Uniqueness test generated by dbt-testgen
    tests:
    - unique
    - not_null
  - name: email
    description: Uniqueness test generated by dbt-testgen
    tests:
    - unique
    - not_null
  - name: user_status
    description: Accepted values test generated by dbt-testgen
    tests:
    - accepted_values:
        values:
        - active
        - inactive
  - name: age
    description: Numeric range test generated by dbt-testgen
    tests:
    - dbt_utils.accepted_range:
        min_value: 22
        max_value: 35
{% endset %}

{{ assert_equal (actual_yaml | trim, expected_yaml | trim) }}