name: Test DBT package

on:
  push:
    branches: [ "main", "develop" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: integration_tests

jobs:
  test-duckdb:
    name: Test on DuckDB
    runs-on: ubuntu-latest
    environment: production
    container:
      image: python:3.11

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: pip install
      run: pip install dbt-core duckdb dbt-duckdb

    - name: Install DBT deps
      run: dbt deps --target duckdb
      
    - name: load test data
      run: dbt seed --target duckdb

    - name: dbt test
      run: dbt test --target duckdb

  test-postgres:
    name: Test on Postgres
    runs-on: ubuntu-latest
    environment: production
    container:
      image: python:3.11

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: pip install
      run: pip install dbt-core duckdb dbt-postgres

    - name: Install DBT deps
      run: dbt deps --target postgres
      
    - name: load test data
      run: dbt seed --target postgres

    - name: dbt test
      run: dbt test --target postgres


      
