name: Test DBT package

on:
  push:
    branches: [ "main", "develop" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: integration_tests

jobs:
  test-duckdb:
    name: Test on DuckDB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: pip install
      run: pip install dbt-core duckdb dbt-duckdb

    - name: Install DBT deps
      run: dbt deps --target duckdb
      
    - name: load test data
      run: dbt seed --target duckdb

    - name: Create seed tests
      run: bash tests/create_seeds_tests_yml.sh

    - name: dbt test
      run: dbt test --target duckdb

  test-postgres:
    name: Test on Postgres
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v4

    - name: pip install
      run: pip install dbt-core dbt-postgres

    - name: Install DBT deps
      run: dbt deps --target postgres
      
    - name: load test data
      run: dbt seed --target postgres

    - name: dbt test
      run: dbt test --target postgres

  test-snowflake:
    name: Test on Snowflake
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - name: pip install
      run: pip install dbt-core dbt-snowflake

    - name: Install DBT deps
      run: dbt deps --target snowflake
      
    - name: load test data
      run: dbt seed --target snowflake

    - name: dbt test
      run: dbt test --target snowflake
