name: Test DBT package

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: integration_tests

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: production
    container:
      image: python:3.11

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: pip install
      run: pip install dbt-core duckdb dbt-duckdb

    - name: Install DBT deps
      run: dbt deps
      
    - name: load test data
      run: dbt seed

    - name: dbt test
      run: dbt test
      
